// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoutFlowAPI.Models;

public partial class Local
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public string Address { get; set; } = null!;

    public string Postalcode { get; set; } = null!;

    public string City { get; set; } = null!;

    public string KeyrespUserid { get; set; } = null!;

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Event> Events { get; set; } = new List<Event>();

    public virtual UserMetadatum KeyrespUser { get; set; } = null!;

    public virtual ICollection<Unit> Units { get; set; } = new List<Unit>();
}