// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoutFlowAPI.Models;

public partial class UserMetadatum
{
    public string FirebaseId { get; set; } = null!;

    public virtual ICollection<Local> Locals { get; set; } = new List<Local>();

    public virtual ICollection<Event> Events { get; set; } = new List<Event>();

    public virtual ICollection<Role> Roles { get; set; } = new List<Role>();

    public virtual ICollection<Unit> Units { get; set; } = new List<Unit>();
}